### ISSUE TITLE
Someone add the gemini 2.5 pro, the 1.5 pro is already very outdated

### ISSUE THREAD

**Issue by jonasbernardo** [leancodepl/arb_translate#28]

**Comment by JulianPscheid** [comment]
I created a [PR with Gemini 2.5 support](https://github.com/leancodepl/arb_translate/pull/29).

For now you can use the updated code by loading this version:
```
dart pub global activate --source git https://github.com/JulianPscheid/arb_translate.git
```

**Comment by MilkBiscuit** [comment]
Could someone take care of this please???
This tool stops working completely if you use gemini. (I haven't tried open-ai yet)

**Comment by JulianPscheid** [comment]
I opened [PR #34 with Gemini 3 support](https://github.com/leancodepl/arb_translate/pull/34) (Gemini 3 Flash, 3.1 Pro, and 3.1 Flash-Lite preview models).

Until it lands upstream you can use it from my fork:
```
dart pub global activate --source git https://github.com/JulianPscheid/arb_translate.git
```

Then in your `l10n.yaml`:
```yaml
arb-translate-model: gemini-3.1-flash-lite-preview
# or: gemini-3-flash-preview / gemini-3.1-pro-preview
arb-translate-api-key: YOUR_GEMINI_API_KEY
```

The fork also still includes the Gemini 2.5 models from [#29](https://github.com/leancodepl/arb_translate/pull/29).
